FLUO_PATH: datasets/Fluo-N2DL-HeLa
FLUO_MEAN: 33203.0
FLUO_STD: 305.0

PHC_PATH: datasets/PhC-C2DH-U373
PHC_MEAN: 0.32636
PHC_STD: 0.03484

DIC_PATH: datasets/DIC-C2DH-HeLa
DIC_MEAN: 0.46680
DIC_STD: 0.04071
