train:
  _target_: src.datasets.SegmentationDataset
  root_path:
    _target_: pathlib.Path
    _args_:
      - ${constants.FLUO_PATH}
  img_folder: "01"
  target_folder: "01_ST/SEG"
  patch_size: [512, 512]
  stride: [256, 256]
  transform:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.RandomRotation
        degrees: 15
      - _target_: torchvision.transforms.RandomHorizontalFlip
        p: 0.5
      - _target_: torchvision.transforms.GaussianBlur
        kernel_size: 5
        sigma: 1.0
      - _target_: torchvision.transforms.Normalize
        mean: ${constants.FLUO_MEAN}
        std: ${constants.FLUO_STD}

val:
  _target_: src.datasets.SegmentationDataset
  root_path:
    _target_: pathlib.Path
    _args_:
      - ${constants.FLUO_PATH}
  img_folder: "02"
  target_folder: "02_ST/SEG"
  patch_size: [512, 512]
  stride: [256, 256]
  transform:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Normalize
        mean: ${constants.FLUO_MEAN}
        std: ${constants.FLUO_STD}
